FROM python:slim-bullseye

ENV DEBIAN_FRONTEND=noninteractive

RUN set -ex \
    && apt-get -qq update \
    && apt-get -qq -y install --no-install-recommends \
        # Non-runtime dependencies
        apt-utils \
        build-essential \
        gnupg2 \
        software-properties-common \
    && apt-add-repository -y contrib \
    && apt-add-repository -y non-free \
    && apt-get -qq update \
    && apt-get -qq -y dist-upgrade \
    # Install dependencies
    && apt-get -qq -y install --no-install-recommends \
        aria2 \
        bash \
        chromium \
        chromium-driver \
        curl \
        ffmpeg \
        figlet \
        git \
        jq \
        libpq-dev \
        libssl-dev \
        libwebp6 \
        libxml2 \
        libxml2-dev \
        libxslt-dev \
        megatools \
        neofetch \
        postgresql \
        pv \
        sudo \
        unar \
        unrar \
        unzip \
        wget \
        xz-utils \
        zip \
    # Install Python modules
    && wget https://raw.githubusercontent.com/KenHV/KensurBot/staging/requirements.txt \
    && pip3 install --no-cache-dir -r requirements.txt \
    && rm requirements.txt \
    # Cleanup
    && apt-get -qq -y purge --auto-remove \
        apt-utils \
        build-essential \
        gnupg2 \
        software-properties-common \
    && apt-get -qq -y clean \
    && rm -rf -- /var/lib/apt/lists/* /var/cache/apt/archives/* /etc/apt/sources.list.d/*

EXPOSE 80 443

CMD ["python3"]

# vim: ft=dockerfile
