name: KensurBot Docker builder

on:
  push:
    paths:
      - "Dockerfile-KensurBot"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1.12.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          file: ./Dockerfile-KensurBot
          platforms: linux/amd64,linux/arm64
          push: true
          tags: kenhv/kensurbot:debian
