name: MirrorBot Docker builder

on:
  push:
    paths:
      - "Dockerfile-MirrorBot"
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-MirrorBot
          platforms: linux/amd64
          push: true
          tags: kenhv/mirrorbot:debian

      - name: Alert via Telegram
        run: |
          function sendTG() {
              curl -s "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendmessage" \
              --data "text=${*}&chat_id=${{ secrets.TELEGRAM_TO }}&parse_mode=Markdown&disable_notification=True"
          }
          sendTG "*MirrorBot docker container has been updated:* [Link](https://hub.docker.com/r/kenhv/mirrorbot/tags)" &> /dev/null
